### ISSUE TITLE
Jessie distro not supported

### ISSUE THREAD

**Issue by abessifi** [mtpereira/ansible-docker-debian#1]
I use Ansible to provision a vagrant VM with this role (ansible-role-docker-debian
), but it seems that it doesn't support Debian Jessie (the VM's system).
Here is the output :

PLAY [jhipster-dev] **********************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [jhipster-dev]

TASK: [mtpereira.docker-debian | main - check if go is installed and version is 1.2] **\* 
changed: [jhipster-dev]

TASK: [mtpereira.docker-debian | go - create build dir] **********************\* 
skipping: [jhipster-dev]

TASK: [mtpereira.docker-debian | go - get source packages] *******************\* 
skipping: [jhipster-dev] => (item=http://ftp.de.debian.org/debian/pool/main/g/golang/golang_1.2-2.dsc)
skipping: [jhipster-dev] => (item=http://ftp.de.debian.org/debian/pool/main/g/golang/golang_1.2.orig.tar.gz)
skipping: [jhipster-dev] => (item=http://ftp.de.debian.org/debian/pool/main/g/golang/golang_1.2-2.debian.tar.gz)

TASK: [mtpereira.docker-debian | go - install build tools] *******************\* 
skipping: [jhipster-dev]

TASK: [mtpereira.docker-debian | go - extract .dsc] **************************\* 
skipping: [jhipster-dev]

TASK: [mtpereira.docker-debian | go - install build dependencies] ************\* 
skipping: [jhipster-dev]

TASK: [mtpereira.docker-debian | go - build package] *************************\* 
skipping: [jhipster-dev]

TASK: [mtpereira.docker-debian | go - install packages] ***********************
skipping: [jhipster-dev] => (item=golang-go-linux-amd64_1.2-2_amd64.deb)
skipping: [jhipster-dev] => (item=golang-src_1.2-2_amd64.deb)
skipping: [jhipster-dev] => (item=golang-go_1.2-2_amd64.deb)
skipping: [jhipster-dev] => (item=golang-doc_1.2-2_all.deb)
skipping: [jhipster-dev] => (item=golang_1.2-2_all.deb)

TASK: [mtpereira.docker-debian | kernel - add backports repo] ****************\* 
ok: [jhipster-dev]

TASK: [mtpereira.docker-debian | kernel - install backported kernel] **********

fatal: [jhipster-dev] => failed to parse: SUDO-SUCCESS-tvzuwcbyuokkbgsnrujtpatkdamtoeyo
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1437008782.25-112048117723750/apt", line 1907, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1437008782.25-112048117723750/apt", line 477, in main
    cache.open(progress=None)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 151, in open
    self._cache = apt_pkg.Cache(progress)
SystemError: E:The value 'wheezy-backports' is invalid for APT::Default-Release as such a release is not available in the sources
FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/vaytess/mongodb-dev.retry

jhipster-dev               : ok=5    changed=1    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by mtpereira** [comment]
Hello!

Indeed, I've written this role specifically for Debian Wheezy and so that is to be expected. As I say in the README, "Wheezy has 2 dependencies missing for docker: golang >= 1.2 and linux kernel >= 3.8.0". This role aims to fix that problem.

This doesn't happen on Debian Jessie, so you should not use this role for installing Docker on it. In fact, installing Docker on Jessie should be much more easy, since those two dependencies are available on the official repositories.

Check out http://docs.docker.com/installation/debian/#debian-jessie-80-64-bit for more information.

Thank you!
